# This rule is not used by the project shopify-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to lukemcewen.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: shopify-operator
    app.kubernetes.io/managed-by: kustomize
  name: discordbot-viewer-role
rules:
- apiGroups:
  - lukemcewen.com
  resources:
  - discordbots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lukemcewen.com
  resources:
  - discordbots/status
  verbs:
  - get
