name: Docker Buildx

on:
  push:
  
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image (development)
        if: github.event_name == 'push'
        run: make docker-buildx IMG=quwen/shopify-operator:${{ github.sha }}

      - name: Build and push Docker image (release)
        if: github.event_name == 'release'
        run: make docker-buildx IMG=${{ secrets.DOCKER_USERNAME }}/shopify-operator:${{ github.event.release.tag_name }}
