name: E2E Tests

on:
  push:

  release:
    types: [published]

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Running Test e2e (development)
        if: github.event_name == 'push'
        env:
          IMG: ${{ secrets.DOCKER_USERNAME }}/shopify-operator:${{ github.sha }}
        run: |
          go mod tidy
          make test-e2e
      
      - name: Running Test e2e (release)
        if: github.event_name == 'release'
        env:
          IMG: ${{ secrets.DOCKER_USERNAME }}/shopify-operator:${{ github.event.release.tag_name }}
        run: |
          go mod tidy
          make test-e2e
