name: E2E Tests

on:
  push:

  release:
    types: [published]

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster
      
      - name: Set IMG variable
        run: |
          if [[ ${{ github.event_name }} == 'release' ]]; then
            echo "IMG=quwen/shopify-operator:${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          else
            echo "IMG=quwen/shopify-operator:${{ github.sha }}" >> $GITHUB_ENV
          fi

      - name: Running Test e2e
        env:
          IMG: ${{ env.IMG }}
        run: |
          go mod tidy
          make test-e2e IMG=${{ env.IMG }}
