name: E2E Tests

on:
  workflow_run:
    workflows: ["Docker Buildx"]
    types:
      - completed

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster
      
      - name: Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag
      
      - name: Read tag
        id: read
        run: echo "tag=$(cat image-tag.txt)" >> $GITHUB_OUTPUT

      - name: Running Test e2e
        env:
          IMG: ${{ secrets.DOCKER_USERNAME }}/shopify-operator:${{ steps.read.outputs.tag }}
        run: |
          go mod tidy
          make test-e2e
